### ISSUE TITLE
Make a default "latest" tag?

### ISSUE THREAD

**Issue by mayli** [tatsushid/docker-tinycore#1]
It would be useful when people want a quick test run.

**Comment by tatsushid** [comment]
That's true. I'll assign a "latest" tag as "6.3-x86_64" alias (will be changed if 6.4 is released) but it will be a different image from the original "6.3-x86_64" though both use the same Dockerfile because of Docker Hub automated build limitation. It would add a duplicate image to your image repository.

**Comment by tatsushid** [comment]
Done. Now you can pull this image without specifying a tag
